dashpay/dashsync-iOS

DashSync/Categories/NSData+Bitcoin.h, DashSync/Categories/NSData+Bitcoin.m, DashSync/Categories/NSMutableData+Dash.h, DashSync/Categories/NSMutableData+Dash.m, DashSync/DashSync.xcdatamodeld/DashSync 1.xcdatamodel/contents, DashSync/Models/DSSimplifiedMasternodeEntry.h, DashSync/Models/DSSimplifiedMasternodeEntry.m, DashSync/Models/Entities/DSSimplifiedMasternodeEntryEntity+CoreDataClass.m, DashSync/Models/Entities/DSSimplifiedMasternodeEntryEntity+CoreDataProperties.h, DashSync/Models/Entities/DSSimplifiedMasternodeEntryEntity+CoreDataProperties.m
See https://github.com/dashpay/dips/pull/30
=> updated simplified masternode entry to 13.0

DashSync/Libraries/AdvancedOperations/Operation Queue/DSOperationQueue.m, DashSync/Libraries/AdvancedOperations/Operations/DSOperation.m, DashSync/Libraries/AdvancedOperations/Operations/NSOperation+DSOperationKit.m
Fixed a rare EXC_BAD_ACCESS crash while removing the operation from `chainOperationsCache` when it was canceled (self was deallocated);
Fixed few places in the code where __weak reference used repeatedly which is potentially unsafe
=> Fixed a rare EXC_BAD_ACCESS crash in DSOperationQueue

DashSync/Libraries/AdvancedOperations/Operation Queue/DSOperationQueue.m, DashSync/Libraries/AdvancedOperations/Operations/DSOperation.h, DashSync/Libraries/AdvancedOperations/Operations/DSOperation.m, DashSync/Models/Managers/Service Managers/Price/DSHTTPGETOperation.h, DashSync/Models/Managers/Service Managers/Price/ParseOperations/DSParseResponseOperation.h
Fixes EXC_BAD_ACCESS crash in finishHandler of operation observer
=> Remove built-in chaining support from DSOperation

DashSync/Models/Managers/Service Managers/Price/ParseOperations/DSParseSparkResponseOperation.m
Spark API may return a response with `null` values when it failed to fetch prices from its source APIs. For instance:
``` json
{
"AED": null,
"AFN": null,
"ALL": null,
"AMD": null,
"ANG": null,
```
=> Fixes crash when Spark API returns invalid response

DashSync/Models/DSBIP39Mnemonic.h, DashSync/Models/DSBIP39Mnemonic.m, DashSync/Models/DSWallet.h, DashSync/Models/DSWallet.m, DashSync/Models/Managers/Chain Managers/DSChainManager.m
`return MIN(1.0,MAX(0.0,0.1 + 0.9*(self.chain.lastBlockHeight - self.syncStartHeight)/(self.chain.estimatedBlockHeight - self.syncStartHeight)));` is just for a random bug I saw.
=> Possibility to define language of Mnemonic at creation

DashSync.podspec, Example/Podfile.lock
Includes https://github.com/dashevo/TinyCborObjc/pull/12 and uses the latest release version of tinycbor dependency.
=> Use an updated version of TinyCborObjc

DashSync/DashSync.m, DashSync/Models/Chain/DSChain.m, DashSync/Models/Managers/Chain Managers/DSChainManager+Protected.h, DashSync/Models/Managers/Chain Managers/DSChainManager.h, DashSync/Models/Managers/Chain Managers/DSChainManager.m, DashSync/Models/Managers/Chain Managers/DSMasternodeManager.h, DashSync/Models/Managers/Chain Managers/DSMasternodeManager.m, DashSync/Models/Managers/Chain Managers/DSTransactionManager.m, DashSync/Models/Wallet/DSSpecialTransactionsWalletHolder.h, DashSync/Models/Wallet/DSSpecialTransactionsWalletHolder.m, DashSync/Models/Wallet/DSWallet.m
The progress bar didn't work all that well, it used to be a specific amount per sync phase, now it will guess the weight of each sync phase and seem more fluid to the end user.
Special transactions that were not part of an account were not having their block height set.
We use weights for different sync phases.
=> weighted progress and special transaction block heights fix when not in an account

DashSync/shared/Models/Wallet/DSAccount.m
This PR removes RBF. RBF is not taken into account in Dash Core and has been deactivated a while ago. Prior to this PR we were marking transactions whose inputs were set to allow RBF as pending until they were mined.
=> removed replace by fee

DashSync/shared/Models/Wallet/DSWallet.h, DashSync/shared/Models/Wallet/DSWallet.m
Small convenience method for getting all transactions for an account along with those not bound to any account.
For convenience.
Not tested, but very small change
=> Small convenience method for getting all transactions for an account.

DashSync/lib/libmerkiOS.a, DashSync/shared/Categories/NSData/NSData+DSMerkAVLTree.m, DashSync/shared/crypto/merk.h
New libs built with updated [c-rust wrapper](https://github.com/dashevo/rs-merk-verify-c-binding)
Now the memory is freed correctly. So memory leaks in wrapper were excluded.
Now the destructor created for the correct memory release of objects created in rust is called.
It was tested using Xcode Instruments pointed out that there is no memory leaks anymore
=> Leak-free destructible merk lib & c header

DashSync/shared/Models/Identity/DSBlockchainIdentity+Protected.h, DashSync/shared/Models/Identity/DSBlockchainIdentity.h, DashSync/shared/Models/Identity/DSBlockchainIdentity.m, DashSync/shared/Models/Keys/DSBLSKey.mm, DashSync/shared/Models/Keys/DSECDSAKey.m, DashSync/shared/Models/Keys/DSKey.h, DashSync/shared/Models/Keys/DSKey.m, Example/Tests/DSTransitionTests.m
We didn't have a method to easily sign message digests for blockchain identities. 
We implemented a method on the blockchain identity to sign a message digest. + some refactoring.
I made a unit test.
=> Added method to sign and verify signature digests

DashSync/shared/Models/Wallet/DSAccount.m, Example/Podfile.lock
Outputs not have nil addresses instead of NSNull null, this was causing a crash on startup if the wallet had transactions with outputs that were not standard addresses.
=> nil address fix

DashSync/shared/Models/Entities/DSDerivationPathEntity+CoreDataClass.h, DashSync/shared/Models/Entities/DSDerivationPathEntity+CoreDataClass.m, DashSync/shared/Models/Identity/DSBlockchainIdentity.m, DashSync/shared/Models/Identity/DSPotentialOneWayFriendship.h, DashSync/shared/Models/Identity/DSPotentialOneWayFriendship.m
Fix the issue when we try to send a contact request and we try to save data into core data from different contexts which leads to the crash.
Whenever we send a contact request and we save data into core data, make sure we always use one core data context
Manually, QA, Tests
N/A
=> Use one context when saving/creating core data entities

DashSync/shared/Models/Identity/DSBlockchainInvitation.m
When we generate a link on iOS side the assetlocktx and islock query items are in uppercased hex encoding and android expecting in lowercase format.
The assetlocktx and islock query items are being generated in lowercased hex encoding
Manually
N/A
=> Encode assetlocktx and islock query items of the invitation link in lowercased hex format

DashSync/shared/Models/DAPI/DSDAPIClient.m
Before, we were retrying peer from `NSSet` using `anyObject` property. The property doesn't return objects randomly and we were facing an issue when we were using the same peer every time.
More info about `anyObject` property of `NSSet` object from docs:
```
One of the objects in the set, or nil if the set contains no objects. The object returned is chosen at the set’s convenience—the selection is not guaranteed to be random.
```
Now we get an array out of `NSSet` using `allObjects` property, then we retrieve a peer by generating a random index using `arc4random_uniform` function.
Manually, Tests
N/A
=> Make sure we initiate dapi network service with a random peer

DashSync/shared/Models/Keys/NSData+Encryption.mm
Fix `encryptWithSecretKey` method and fix `testBLSEncryptionAndDecryption` test. 
Use the legacy way to serialize bls elements
Tests
N/A
=> Use the legacy way to serialize bls elements

DashSync/shared/Models/Managers/Chain Managers/DSTransactionManager.h, DashSync/shared/Models/Managers/Chain Managers/DSTransactionManager.m
The error in `publishTransaction` is nullable but not marked as such. This makes it impossible to nil-check in Swift.
manually
n/a
=> fix: swift error interop for publishTransaction

DashSync/shared/Models/Managers/Service Managers/DSPriceManager.m
When `fiatCurrencyString` is called with a custom currency code, the returned amount is calculated correctly but the currency code is wrong - it is set to the local currency code.
To format the currency correctly, the `localFormat.currencyCode` is changed before formatting and then restored to the original value.
manually
=> fix: wrong currency code returned from fiatCurrencyString

DashSync/shared/Models/Derivation Paths/DSCreditFundingDerivationPath.m, DashSync/shared/Models/Derivation Paths/DSMasternodeHoldingsDerivationPath.m, DashSync/shared/Models/Wallet/DSAccount.h, DashSync/shared/Models/Wallet/DSAccount.m, DashSync/shared/Models/Wallet/DSWallet+Protected.h, DashSync/shared/Models/Wallet/DSWallet.h, DashSync/shared/Models/Wallet/DSWallet.m
Introduce a method to sign a tx without entering pin
Manually
N/A
=> feat: Introduce a method to sign a tx without entering pin

DashSync/shared/Models/Managers/Service Managers/Auth/DSAuthenticationManager.m
Currently we presenting view controller from auth manager inside the current view controller and it leads to wrong layout of the presenting controller. In this PR we made a small fix in order to present the presenting view controller on top of the screen.
Manually
N/A
=> feat(ui): Present view controllers from auth manager on top of the current context

DashSync/shared/Models/Managers/Chain Managers/DSKeyManager.m
Keychain locations for BLS (basic) and ED 25519 has changed 
Needed for those who already generate keys with wrong derivation scheme and stored them in keychain
=> fix: change key storage locations for bls basic and ed25519

DashSync/shared/Models/Managers/Chain Managers/DSMasternodeManager.m
Fix: filename suffix for list diffs
=> fix: diff files were storing with bad protocol versions

DashSync/shared/Libraries/DSLogger.m
We log some info in rust into separated file. So it would be great to attach it to other logs while sending them from device 
Checked in simulator
=> chore: attach rust log file for sending

DashSync.podspec, DashSync/shared/DashSync.m, DashSync/shared/Models/Chain/DSChain.m, DashSync/shared/Models/Entities/DSSimplifiedMasternodeEntryEntity+CoreDataClass.m, DashSync/shared/Models/Managers/Chain Managers/DSChainManager.m, DashSync/shared/Models/Managers/Chain Managers/DSGovernanceSyncManager.m, DashSync/shared/Models/Managers/Chain Managers/DSMasternodeManager.m, DashSync/shared/Models/Managers/Chain Managers/DSPeerManager.h, DashSync/shared/Models/Managers/Chain Managers/DSPeerManager.m, DashSync/shared/Models/Managers/Chain Managers/DSSporkManager.m, DashSync/shared/Models/Managers/Chain Managers/DSTransactionManager.m, DashSync/shared/Models/Masternode/DSMasternodeListService.m, DashSync/shared/Models/Masternode/DSMasternodeListStore.m, DashSync/shared/Models/Masternode/DSQuorumRotationService.m, DashSync/shared/Models/Network/DSPeer.h, DashSync/shared/Models/Network/DSPeer.m, Example/Podfile.lock
Fix: some thread-safety issues
Add disconnect reason entity
=> fix: multithreading issue part 2

DashSync/shared/Models/Identity/DSBlockchainIdentity.h, DashSync/shared/Models/Identity/DSBlockchainIdentity.m
`BlockchainIdentity.registerOnNetwork` is called for more than one purpose: to create a user identity and to create an invitation. However, the PIN code message says "Would you like to create this user?" for both scenarios.
- Change `registerOnNetwork` signature so that it accepts the prompt from a caller.
=> fix: accept a prompt argument for identity.registerOnNetwork

DashSync/shared/Models/Managers/Service Managers/Price/FetchOperations/DSFetchDashRetailPricesOperation.m
- Replaced `dashretail.org` with `ctx.com` which is an alias for the same source.
QA
=> fix: change the source of exchange rates

DashSync/shared/Models/Chain/DSChainConstants.h, DashSync/shared/Models/CoinJoin/DSCoinControl.h, DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.h, DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.m, DashSync/shared/Models/Transactions/Base/DSTransaction.h, DashSync/shared/Models/Transactions/Base/DSTransaction.m, DashSync/shared/Models/Wallet/DSAccount.h, DashSync/shared/Models/Wallet/DSAccount.m, Example/DashSync/DSCoinJoinViewController.m
For various CoinJoin functions we need the `availableCoins` function which would count outputs suitable for the required purpose.
https://github.com/dashpay/dashj/blob/feature-coinjoin/core/src/main/java/org/bitcoinj/wallet/WalletEx.java#L739
https://github.com/dashpay/dash/blob/master/src/wallet/wallet.cpp#L2536
- `availableCoins` method
- `hasCollateralInputs` method
N/A
=> feat(coinjoin): availableCoins method

DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.h, DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.m, DashSync/shared/Models/CoinJoin/DSCompactTallyItem.h, DashSync/shared/Models/CoinJoin/DSCompactTallyItem.m, DashSync/shared/Models/CoinJoin/DSInputCoin.h, DashSync/shared/Models/CoinJoin/DSInputCoin.m, DashSync/shared/Models/Transactions/Base/DSTransaction.h, Example/DashSync/DSCoinJoinViewController.m
`selectCoinsGroupedByAddresses` method needs to be implemented.
The implementation is split between DashSync and dash-shared-core:
- dash-shared-core will contain the cache and will check and return the cache if possible.
- DashSync will contain the logic to calculate the result otherwise.
N/A
=> feat(coinjoin): selectCoinsGroupedByAddresses

Example/DashSync.xcodeproj/project.pbxproj, Example/Podfile.lock
See https://github.com/dashpay/dashwallet-ios/pull/646
=> chore: update protobuf version to include privacy file

DashSync/shared/Models/Managers/Chain Managers/DSTransactionManager.m
Check if the address is nil before calling `transactionCreationCompletion` to avoid a crash.
QA
=> fix: nil address check

DashSync/shared/Models/CoinJoin/DSCoinJoinManager.h, DashSync/shared/Models/CoinJoin/DSCoinJoinManager.m, DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.h, DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.m
On repeated runs of `do_automatic_denominating`, the balance passed from obj-c is wrong.
- Refactor `wrapper` and `manager` to switch them logically
- Recalculate balance info before running CoinJoin
N/A
=> feat(coinjoin): recalculate balance

DashSync/shared/Models/CoinJoin/DSTransaction+CoinJoin.m
`sign_collateral` fails because tx inputs don't have inScript.
- Get the actual inScript data if the input comes from Rust empty.
N/A
=> fix(coinjoin): sign collateral

DashSync/shared/Models/CoinJoin/DSCoinJoinManager.h, DashSync/shared/Models/CoinJoin/DSCoinJoinManager.m, DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.m, DashSync/shared/Models/Managers/Chain Managers/DSPeerManager.h, DashSync/shared/Models/Managers/Chain Managers/DSPeerManager.m
- DSA message needs to be sent after `join_existing_queue` is called.
- Sending DSA to a connected masternode. This is just a "proof of concept" as later we'll have a DashJ's `MasternodeGroup` analog for handling conjoin connections.
NA
=> feat: sending DSA to a connected masternode

DashSync/shared/Models/Managers/Service Managers/DSPriceManager.h, DashSync/shared/Models/Managers/Service Managers/DSPriceManager.m, DashSync/shared/Models/Managers/Service Managers/Price/DSPriceOperationProvider.h, DashSync/shared/Models/Managers/Service Managers/Price/DSPriceOperationProvider.m, DashSync/shared/Models/Managers/Service Managers/Price/FetchOperations/DSFetchDashRetailPricesOperation.m, DashSync/shared/Models/Managers/Service Managers/Price/FetchOperations/DSFetchFirstFallbackPricesOperation.m, DashSync/shared/Models/Managers/Service Managers/Price/FetchOperations/DSFetchPricesOperation.h, DashSync/shared/Models/Managers/Service Managers/Price/FetchOperations/DSFetchSecondFallbackPricesOperation.m, DashSync/shared/Models/Wallet/DSWalletConstants.m, Example/Podfile.lock
Some changes are required to support stale rate reporting.
- Add error reporting to the `fetchCompletion`
- Save last rates retrieval time
- Add `isVolatile` field for more than 50% change in price within 7 days
QA
=> feat: support stale rates

DashSync/shared/Models/Derivation Paths/DSFundsDerivationPath.m
`registerAddressesWithGapLimit` call crashes on `NSAssert(self.addressesLoaded` in a newly added CoinJoin derivation path because the XPub hasn't been created yet and addresses aren't loaded
- Skip `registerAddressesWithGapLimit` if addresses aren't loaded
=> fix(coinjoin): derivation path crash

DashSync/shared/Models/CoinJoin/DSCoinControl.h, DashSync/shared/Models/CoinJoin/DSCoinControl.m, DashSync/shared/Models/CoinJoin/DSCoinJoinManager.h, DashSync/shared/Models/CoinJoin/DSCoinJoinManager.m, DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.m, DashSync/shared/Models/Wallet/DSAccount.h, DashSync/shared/Models/Wallet/DSAccount.m
Inputs for CoinJoin transactions are taken from already-denominated inputs which is an error.
Leverage CoinControll to limit inputs while forming a transaction.
dash-shared-core: https://github.com/dashpay/dash-shared-core/pull/89
=> fix(coinjoin): using coin_control to limit inputs for CJ transactions

DashSync/shared/Models/CoinJoin/DSCoinControl.m, DashSync/shared/Models/CoinJoin/DSCoinJoinManager.m, DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.m, DashSync/shared/Models/CoinJoin/Utils/DSMasternodeGroup.m, DashSync/shared/Models/Wallet/DSAccount.m
MasternodeGroup is largely ported from DashJ. This means it drags in some DashJ-specific stuff since it is based on general-purpose PeerGroup. Some issues prevent it from being connected to the right masternodes at the right time.
Simplify `MasternodeGroup` to only connect to the masternodes connected to an active session.
N/A
=> fix(coinjoin): simplify MasternodeGroup

Example/Podfile
Since XCode version 16, build of Dashsync was failing with:
`clang: error: unsupported option '-G' for target 'arm64-apple-xxx` (depending on the destination)
This originated from the pod BoringSSL-GRPC.
The issue is already reported in https://github.com/grpc/grpc/issues/36888
The fix consists of removing all flags `GCC_WARN_INHIBIT_ALL_WARNINGS` when building and installing pod BoringSSL-GRPC.
locally
no
=> fix: pod install for xcode 16

.github/workflows/build.yml, .github/workflows/coverage.yml, .github/workflows/e2eTestsTestnet.yml, .github/workflows/lint.yml, .github/workflows/network.yml, .github/workflows/syncTestMainnet.yml, .github/workflows/syncTestTestnet.yml, .github/workflows/test.yml, DashSync.podspec, DashSync/shared/Models/Managers/Chain Managers/DSBackgroundManager.m, Example/DashSync.xcodeproj/project.pbxproj, Example/Podfile, Example/Podfile.lock
Check Network flow was reporting `This request has been automatically failed because it uses a deprecated version of actions/upload-artifact: v2`
Bumped to upload-artifact: v4.
=> fix: check network GH workflow

DashSync.podspec, DashSync/shared/Models/DAPI/DSPlatformDocumentsRequest.m, DashSync/shared/Models/DAPI/Networking/DSDAPIPlatformNetworkService.m, DashSync/shared/Models/DAPI/Networking/DSDAPIPlatformNetworkServiceProtocol.h, DashSync/shared/Models/Identity/DSBlockchainIdentity.m, DashSync/shared/Models/Managers/Chain Managers/DSMasternodeManager.m, DashSync/shared/Models/Masternode/DSMasternodeListDiffService.m, DashSync/shared/Models/Masternode/DSMasternodeListService.h, DashSync/shared/Models/Masternode/DSMasternodeListService.m, DashSync/shared/dpns-contract.json, Example/DashSync.xcodeproj/project.pbxproj, Example/Podfile.lock, Gemfile
Reverts dashpay/dashsync-iOS#560
=> Revert "feat: migrations for Platform v0.22 to v1"

DashSync/shared/Libraries/DSLogger.m, DashSync/shared/Libraries/Logs/CompressingLogFileManager.h, DashSync/shared/Libraries/Logs/CompressingLogFileManager.m, DashSync/shared/Models/Network/DSPeer.m
We want to zip logs to get more information from users.
- `CompressingLogFileManager` adapted from CocoaLumberjack demos.
- Added compression for Rust logs.
QA
=> feat(coinjoin): zip logs

DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.h, DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.m, DashSync/shared/Models/CoinJoin/DSTransaction+CoinJoin.m, DashSync/shared/Models/CoinJoin/Utils/DSMasternodeGroup.m, DashSync/shared/Models/Transactions/Base/DSTransaction.h, DashSync/shared/Models/Transactions/Base/DSTransaction.m
Calculating the amount and direction can take a long time, especially for CoinJoin transactions.
- Cache direction and amount
- Some synchronization fixes
QA
=> feat(coinjoin): cache transaction amount and direction

DashSync/shared/Models/CoinJoin/DSCoinControl.h, DashSync/shared/Models/CoinJoin/DSCoinControl.m, DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.m, DashSync/shared/Models/Transactions/Base/DSTransaction.m, DashSync/shared/Models/Wallet/DSAccount.m
CoinControl doesn't account for the `destination_change` parameter which can lead the change to be returned to a wrong address.
- Implemented `destination_change`
dash-shared-core: https://github.com/dashpay/dash-shared-core/pull/102
QA
=> fix(coinjoin): add destination_change to coin control

DashSync/shared/Models/CoinJoin/DSCoinJoinManager.h, DashSync/shared/Models/CoinJoin/DSCoinJoinManager.m
For the invite screen changes, we need a method to check if `assetLockTx` is mixed or not.
- Expose appropriate CoinJoin methods.
QA
=> feat: allow the client to check if an amount is denominated

DashSync/shared/Models/Identity/DSIdentity+Username.m, DashSync/shared/Models/Identity/DSIdentity.h, DashSync/shared/Models/Identity/DSIdentity.m, DashSync/shared/Models/Managers/Chain Managers/DSIdentitiesManager.h, DashSync/shared/Models/Managers/Chain Managers/DSIdentitiesManager.m, DashSync/shared/Models/Persistence/DSDataController.m
This pull request introduces several improvements and fixes across the `DashSync` project, focusing on error handling, logging, identity registration, and search functionality. Key changes include enhanced error reporting, new convenience methods for identity registration status, and the restoration of previously commented-out methods for searching identities.
* Enhanced logging in `DSIdentity+Username.m` to include detailed debug information and error messages during username registration. Errors are now passed to completion handlers instead of being ignored.
* Updated `DSDataController.m` to enable automatic merging of changes from the parent context in the `platformContext`, improving data consistency.
* Added a new `isUnknown` property to `DSIdentity` to check if the registration …
=> chore: some additional errors propagation
