dashpay/dashsync-iOS

DashSync/Models/DSDerivationPath.h
DashSync/Models/DSDerivationPath.m
Example/DashSync.xcodeproj/project.pbxproj
Example/DashSync/Base.lproj/Main.storyboard
Example/DashSync/DSAddressesExporterViewController.h
Example/DashSync/DSAddressesExporterViewController.m
Example/DashSync/DSDerivationPathsAddressesViewController.m

This just gives a feature for exporting a list of addresses.

export addresses

---

.tx/config

Workflow for DashSync is the same as in DashWallet: https://github.com/QuantumExplorer/dashwallet/pull/35

Configured transifex for DashSync

---

DashSync/Models/Managers/Chain Managers/DSMasternodeManager.m

Just noticed this could be an issue.

ignore old masternode diffs

---

DashSync/Models/Managers/Service Managers/Price/DSPriceOperationProvider.m
DashSync/Models/Managers/Service Managers/Price/FetchOperations/DSFetchDashRetailPricesOperation.h
DashSync/Models/Managers/Service Managers/Price/FetchOperations/DSFetchDashRetailPricesOperation.m
DashSync/Models/Managers/Service Managers/Price/Requests/DSHTTPDashRetailOperation.h
DashSync/Models/Managers/Service Managers/Price/Requests/DSHTTPDashRetailOperation.m

(cherry picked from commit e7c3dc0ab662350c4a4cc1b48fe89853f20d0610)

Fix missing Dashretail price sourcing operation

---

DashSync/Categories/NSString+Dash.h
DashSync/Categories/NSString+Dash.m
DashSync/Models/DSLocalMasternode.h
DashSync/Models/DSLocalMasternode.m
DashSync/Models/DSSimplifiedMasternodeEntry.h
DashSync/Models/DSSimplifiedMasternodeEntry.m
DashSync/Models/DSWallet.h
DashSync/Models/DSWallet.m
DashSync/Models/Keys/DSBLSKey.mm
DashSync/Models/Keys/DSECDSAKey.h
DashSync/Models/Keys/DSECDSAKey.m
DashSync/Models/Keys/DSKey.h
DashSync/Models/Managers/Chain Managers/DSMasternodeManager.h
DashSync/Models/Managers/Chain Managers/DSMasternodeManager.m

mostly just convenience methods

improvements for masternode features

---

DashSync/Models/Chain/DSChain.m
DashSync/Models/Masternode/DSMasternodeList.m
DashSync/Models/Wallet/DSBIP39Mnemonic.h
Example/Tests/DSSyncTests.m

fixed issue where chain sync would go at same time as terminal sync

---

DashSync/Models/Persistence/DSDataController.m

Fixed compilation in Release configuration.
Changed how `storeURL` method was called since the internal API of DSDataController had been changed.
cmd + B
No

Fix builing in Release configuration

---

DashSync/Models/Chain/DSChain.h
DashSync/Models/Chain/DSChain.m
DashSync/Models/Managers/Chain Managers/DSChainManager.h
DashSync/Models/Managers/Chain Managers/DSChainManager.m
DashSync/Models/Managers/Chain Managers/DSMasternodeManager.m
DashSync/Models/Managers/Chain Managers/DSTransactionManager.m
Example/DashSync/DSSyncViewController.m

reset works without crashing even during masternode list download

---

DashSync/DashSync.xcdatamodeld/DashSync 7.xcdatamodel/contents
DashSync/Models/Entities/DSFriendRequestEntity+CoreDataProperties.h
DashSync/Models/Entities/DSFriendRequestEntity+CoreDataProperties.m
DashSync/Models/Identity/DSBlockchainIdentity.m
DashSync/Models/Identity/DSPotentialOneWayFriendship.h
DashSync/Models/Identity/DSPotentialOneWayFriendship.m
Example/Tests/DSSyncTests.m

This is needed to sort notifications

Added a timestamp field to contact requests

---

Example/Podfile.lock

Update pods using in the Example app

---

DashSync/DashSync.m
DashSync/Models/Chain/DSChain.m
DashSync/Models/Managers/Chain Managers/DSChainManager.h
DashSync/Models/Managers/Chain Managers/DSPeerManager.m
DashSync/Models/Managers/Chain Managers/DSTransactionManager.h
DashSync/Models/Managers/Chain Managers/DSTransactionManager.m
DashSync/Models/Managers/Service Managers/DSEventManager.m
DashSync/Models/Wallet/DSWalletConstants.m
Example/DashSync/DSSyncViewController.m
Example/DashSync/DSTransactionsViewController.m
Example/DashSync/Masternodes.storyboard

send off a new notification on estimated last block change

---

DashSync/Models/Managers/Service Managers/DSInsightManager.h
DashSync/Models/Managers/Service Managers/DSInsightManager.m
DashSync/Models/Wallet/DSBIP39Mnemonic.h
DashSync/Models/Wallet/DSBIP39Mnemonic.m

added methods for finding missing passphrase words

---

DashSync/Models/Wallet/DSBIP39Mnemonic.h
DashSync/Models/Wallet/DSBIP39Mnemonic.m

small fixes

---

DashSync/Models/Wallet/DSBIP39Mnemonic.m

always allow one processor

---

DashSync/DashSync.xcdatamodeld/DashSync 8.xcdatamodel/contents
DashSync/Models/Derivation Paths/DSAuthenticationKeysDerivationPath.h
DashSync/Models/Derivation Paths/DSAuthenticationKeysDerivationPath.m
DashSync/Models/Derivation Paths/DSDerivationPath.h
DashSync/Models/Derivation Paths/DSDerivationPathFactory.m
DashSync/Models/Derivation Paths/DSFundsDerivationPath.m
DashSync/Models/Derivation Paths/DSIncomingFundsDerivationPath.m
DashSync/Models/Derivation Paths/DSSimpleIndexedDerivationPath.m
DashSync/Models/Entities/DSAddressEntity+CoreDataProperties.h
DashSync/Models/Entities/DSAddressEntity+CoreDataProperties.m
Example/DashSync.xcodeproj/project.pbxproj
Example/DashSync/DSAccountsDerivationPathsViewController.m
Example/DashSync/DSChainsViewController.m
Example/DashSync/DSDoubleDerivationPathsAddressesViewController.h
Example/DashSync/DSDoubleDerivationPathsAddressesViewController.m
Example/DashSync/DSIdentityAuthenticationDerivationPathsAddressesViewController.h
Example/DashSync/DSIdentityAuthenticationDerivationPathsAddressesViewController.m
Example/DashSync/DSSpecializedDerivationPathsViewController.m
Example/DashSync/DSStandaloneDerivationPathViewController.m
Example/DashSync/Wallets.storyboard

Addresses were not properly being displayed in the specialized derivation paths. This led to confusion about proper keys.

Fixed identity authentication addresses generation and UI

---

DashSync/Models/Wallet/DSAccount.m

deal with null addresses

---

DashSync/Models/Managers/Chain Managers/DSChainManager.m

deal with div by 0 that should not be possible

---

DashSync/Models/Managers/Chain Managers/DSMasternodeManager.m

allow Insight Blocks for verification on testnet

---

DashSync/Models/Chain/DSChain.m
DashSync/Models/Entities/DSTransactionEntity+CoreDataClass.m
DashSync/Models/Managers/Chain Managers/DSMasternodeManager.h
DashSync/Models/Managers/Chain Managers/DSMasternodeManager.m
DashSync/Models/Transactions/Base/DSTransaction+Protected.h
DashSync/Models/Transactions/Base/DSTransaction.m

Fixed an issue where chain sync and sending could pause during masternode list saving

Better block and transaction saving.

---

DashSync/Categories/NSArray+Dash.h
DashSync/Categories/NSArray+Dash.m
DashSync/DashSync.m
DashSync/Models/Chain/DSChain+Protected.h
DashSync/Models/Chain/DSChain.m
DashSync/Models/Managers/Chain Managers/DSChainManager+Protected.h
DashSync/Models/Managers/Chain Managers/DSChainManager.h
DashSync/Models/Managers/Chain Managers/DSChainManager.m
DashSync/Models/Managers/Chain Managers/DSMasternodeManager.m
DashSync/Models/Managers/Chain Managers/DSPeerManager.h
DashSync/Models/Managers/Chain Managers/DSPeerManager.m
DashSync/Models/Masternode/DSMasternodeList.h
DashSync/Models/Masternode/DSMasternodeList.m
DashSync/Models/Wallet/DSWalletConstants.m

This PR fixes some issues around connectivity and the estimated block height.

better connectivity

---

DashSync.podspec
Example/Podfile.lock
bls-signatures-pod/bls-signatures-pod.podspec

Support building on Apple Silicon

---

DashSync/Models/Persistence/Migration/Internal/DSCoreDataMigrationVersion.h
DashSync/Models/Persistence/Migration/Internal/DSCoreDataMigrationVersion.m

Set current CoreData version

---

DashSync/Models/Managers/Chain Managers/DSMasternodeManager.m
DashSync/Models/Masternode/DSQuorumEntry.m

fixed the proper threshold for 10 member quorums

---

DashSync/Categories/NSData+Bitcoin.h
DashSync/Categories/NSData+Bitcoin.m
DashSync/DashSync.xcdatamodeld/.xccurrentversion
DashSync/DashSync.xcdatamodeld/DashSync 10.xcdatamodel/contents
DashSync/Models/Entities/DSDashpayUserEntity+CoreDataProperties.h
DashSync/Models/Entities/DSDashpayUserEntity+CoreDataProperties.m
DashSync/Models/Identity/DSBlockchainIdentity.h
DashSync/Models/Identity/DSBlockchainIdentity.m
DashSync/Models/Identity/DSTransientDashpayUser+Protected.h
DashSync/Models/Identity/DSTransientDashpayUser.h
DashSync/Models/Identity/DSTransientDashpayUser.m
DashSync/Models/Persistence/Migration/Internal/DSCoreDataMigrationVersion.h
DashSync/Models/Persistence/Migration/Internal/DSCoreDataMigrationVersion.m
Example/DashSync/DSContactProfileViewController.m
Example/Podfile
Example/Podfile.lock

image hashing

---

Example/Podfile
Example/Podfile.lock

Bump CocoaImageHashing version

---

DashSync/Models/DAPI/Networking/DSDAPIPlatformNetworkServiceProtocol.h
DashSync/Models/Identity/DSBlockchainIdentity.m

Hotfix to fix incoming requests.

fixed issue with incomming requests

---

DashSync/DashSync.m

Minor background execution fix

---

DashSync/Models/Managers/Service Managers/DSPriceManager.m

Fix PriceFormatter crash for Bulgarian users

---

.github/workflows/network.yml
Example/DashSync.xcodeproj/xcshareddata/xcschemes/NetworkInfo.xcscheme
Example/NetworkInfo/DSNetworkInfo.h
Example/NetworkInfo/DSNetworkInfo.m
Example/NetworkInfo/main.m

improved NetworkInfo

---

DashSync/shared/Models/Derivation Paths/DSSimpleIndexedDerivationPath.m
DashSync/shared/Models/Managers/Chain Managers/DSMasternodeManager.m
DashSync/shared/Models/Transactions/Base/DSInstantSendTransactionLock.m
Example/NetworkInfo/DSNetworkInfo.m

various fixes

---

DashSync/shared/Models/Wallet/DSBIP39Mnemonic.m

fixed mnemonic recovery crash

---

DashSync/shared/Categories/NSArray+Dash.h
DashSync/shared/Categories/NSArray+Dash.m
DashSync/shared/Categories/NSMutableArray+Dash.h
DashSync/shared/Categories/NSMutableArray+Dash.m
DashSync/shared/Models/Wallet/DSBIP39Mnemonic.m

improved memory allocation security

---

.github/workflows/e2eTestsTestnet.yml
Example/Tests/CryptoTests.xctestplan
Example/Tests/DSDIP14Tests.m
Example/Tests/GovernanceTests.xctestplan
Example/Tests/LibraryTests.xctestplan
Example/Tests/MainnetSyncTests.xctestplan
Example/Tests/MasternodeListTests.xctestplan
Example/Tests/Metrics.xctestplan
Example/Tests/PaymentTests.xctestplan
Example/Tests/PlatformTransitionTests.xctestplan
Example/Tests/TestnetE2ETests.xctestplan
Example/Tests/TestnetSyncTests.xctestplan
Example/Tests/TransactionTests.xctestplan
Example/Tests/WalletTests.xctestplan

fixed testplan

---

.tx/config

Fix Transifex config

---

DashSync/shared/Models/Chain/DSChain.h
DashSync/shared/Models/Chain/DSChain.m
DashSync/shared/Models/Entities/DSMerkleBlockEntity+CoreDataClass.h
DashSync/shared/Models/Entities/DSMerkleBlockEntity+CoreDataClass.m
DashSync/shared/Models/Identity/DSBlockchainIdentity.m
DashSync/shared/bg.lproj/Localizable.strings
DashSync/shared/cs.lproj/Localizable.strings
DashSync/shared/de.lproj/Localizable.strings
DashSync/shared/el.lproj/Localizable.strings
DashSync/shared/en.lproj/Localizable.strings
DashSync/shared/es.lproj/Localizable.strings
DashSync/shared/fr.lproj/Localizable.strings
DashSync/shared/id.lproj/Localizable.strings
DashSync/shared/it.lproj/Localizable.strings
DashSync/shared/ja.lproj/Localizable.strings
DashSync/shared/ko.lproj/Localizable.strings
DashSync/shared/nl.lproj/Localizable.strings
DashSync/shared/pl.lproj/Localizable.strings
DashSync/shared/pt.lproj/Localizable.strings
DashSync/shared/ru.lproj/Localizable.strings
DashSync/shared/sk.lproj/Localizable.strings
DashSync/shared/th.lproj/Localizable.strings
DashSync/shared/tr.lproj/Localizable.strings
DashSync/shared/vi.lproj/Localizable.strings
DashSync/shared/zh-Hans.lproj/Localizable.strings
DashSync/shared/zh-Hant-TW.lproj/Localizable.strings

5.4.1 Fixes

---

DashSync/shared/Models/Identity/DSBlockchainIdentity.m
DashSync/shared/Models/Managers/Chain Managers/DSMasternodeManager.m

lowered time outs for registration from 5 mins to 25 seconds

---

DashSync/shared/Models/Chain/DSChain.h
DashSync/shared/Models/Chain/DSChain.m
DashSync/shared/Models/Derivation Paths/DSDerivationPath.m
DashSync/shared/Models/Derivation Paths/DSDerivationPathFactory.m
DashSync/shared/Models/Identity/DSBlockchainIdentity.m
DashSync/shared/Models/Managers/Chain Managers/DSChainManager.m
DashSync/shared/Models/Network/DSPeer.m
DashSync/shared/Models/Wallet/DSWallet.m

fixes for v18

---

DashSync/shared/Models/Chain/DSBlock.m

improve dark gravity wave logs on difficulty error

---

DashSync/shared/Models/Managers/Chain Managers/DSTransactionManager.m

remove old instant send locks waiting for quorums

---

DashSync/shared/Models/Identity/DSBlockchainIdentity.m
DashSync/shared/Models/Managers/Service Managers/DSShapeshiftManager.m

Context and thread safety fixes

---

DashSync/shared/Models/Managers/Chain Managers/DSMasternodeManager.m

MASTERNODE_LIST_ADDED_NODES -> MASTERNODE_LIST_REMOVED_NODES (incorrectly marked)

---

DashSync/shared/Libraries/DSPermissionNotification.h
DashSync/shared/Libraries/DSPermissionNotification.m
DashSync/shared/Models/Managers/Service Managers/Auth/DSBiometricsAuthenticator.m

Post notifications before and after biometrics authentication #NMI-555

---

DashSync/shared/Models/Payment/DSPaymentProtocol.h
DashSync/shared/Models/Payment/DSPaymentProtocol.m
DashSync/shared/Models/Payment/DSPaymentRequest.h
DashSync/shared/Models/Payment/DSPaymentRequest.m

improvements for callback in bip70

---

DashSync/shared/Models/Managers/Chain Managers/DSTransactionManager.m

This is a fix where the wallet only will publish a transaction till after acknowledgment.

publish transaction only after ack

---

DashSync/shared/Categories/BigIntTypes.h
DashSync/shared/Models/Transactions/Base/DSTransaction.m
DashSync/shared/Models/Transactions/Base/DSTransactionInput.h
DashSync/shared/Models/Transactions/Base/DSTransactionInput.m
DashSync/shared/Models/Transactions/Base/DSTransactionOutput.h
DashSync/shared/Models/Transactions/Base/DSTransactionOutput.m
DashSync/shared/Models/Wallet/DSWallet.h
DashSync/shared/Models/Wallet/DSWallet.m
Example/Tests/DSProviderTransactionsTests.m

small comparison improvement

---

.gitattributes

Mark Mac OS merk lib for use with Git LFS 

[git lfs for mac os merk lib]

---

Example/DashSync.xcodeproj/project.pbxproj
Example/Tests/DSProviderTransactionsTests.m

Fix tests that were broken after implementation of separate transaction's inputs/outputs.
BackgroundTasks.framework became optional for linking in tests target

Fix tests branch

---

.github/workflows/e2eTestsTestnet.yml
.github/workflows/syncTestMainnet.yml
DashSync/shared/Models/DAPI/DSPlatformTreeQuery.m
DashSync/shared/Models/DAPI/Networking/DSDAPIPlatformNetworkService.m
DashSync/shared/Models/Managers/Chain Managers/DSIdentitiesManager.m
DashSync/shared/Models/Transactions/Base/DSTransaction.m

fix: Last CI fix

---

.github/workflows/build.yml
.github/workflows/coverage.yml
.github/workflows/lint.yml
.github/workflows/network.yml
.github/workflows/syncTestMainnet.yml
.github/workflows/syncTestTestnet.yml
.github/workflows/test.yml

fix: changed lfs caching for all tests

---

.github/workflows/build.yml
.github/workflows/coverage.yml
.github/workflows/lint.yml
.github/workflows/network.yml
.github/workflows/syncTestMainnet.yml
.github/workflows/syncTestTestnet.yml
.github/workflows/test.yml

Reverts dashevo/dashsync-iOS#427

Revert "fix: changed lfs caching for all tests"

---

DashSync/shared/Models/DAPI/Networking/DSDAPIGRPCResponseHandler.m
DashSync/shared/Models/Identity/DSBlockchainIdentity.m
DashSync/shared/Models/Identity/DSBlockchainInvitation.m

Fix indentations 
N/A
Fixed indentations in a bunch of files
N/A

Fix indentations

---

DashSync.podspec
DashSync/shared/Models/Keys/DSBLSKey+Private.h
Example/DashSync.xcodeproj/project.pbxproj
Example/Podfile
Example/Podfile.lock
bls-signatures-pod/bls-signatures-pod.podspec

fix: build bls signatures pod on apple silicon

---

DashSync.podspec
Example/Podfile.lock

This is an update that points to a new dash-shared-core version.
- [] I have commented my code, particularly in hard-to-understand areas

[update DashSharedCore to 0.1.4]

---

DashSync/shared/Models/Managers/Service Managers/DSPriceManager.h
DashSync/shared/Models/Managers/Service Managers/DSPriceManager.m

Introduce new number formatter that we are using during csv export
DSPriceManager now contains `csvDashFormat` property
Manually
N/A

Introduce csv number formatter

---

DashSync/shared/DashSync.xcdatamodeld/.xccurrentversion
DashSync/shared/DashSync.xcdatamodeld/DashSync 15.xcdatamodel/contents
DashSync/shared/Models/Entities/DSTransactionEntity+CoreDataClass.m
DashSync/shared/Models/Entities/DSTransactionEntity+CoreDataProperties.h
DashSync/shared/Models/Entities/DSTransactionEntity+CoreDataProperties.m
DashSync/shared/Models/Identity/DSBlockchainIdentity.m
DashSync/shared/Models/Transactions/Base/DSTransaction.h
DashSync/shared/Models/Transactions/Base/DSTransaction.m

Tax categories support 
Introduce new attribute in transaction entity that stores tx tax category
Tests, Q/A, Manually
N/A

Tax categories support 

---

DashSync/shared/Models/Persistence/Migration/Internal/DSCoreDataMigrationVersion.h
DashSync/shared/Models/Persistence/Migration/Internal/DSCoreDataMigrationVersion.m

Fix CoreData Migration
Added the last and previous versions of core data into the list.
iOS Client
N/A

Fix/Core Data Migration

---

DashSync/shared/Models/Transactions/Base/DSTransaction.m
DashSync/shared/Models/Wallet/DSAccount.m

Memory consumption optimizations
Profiling, Manually
N/A

feat: Data retrieval optimization

---

DashSync/shared/Models/Masternode/DSQRInfoProcessingResult.m
DashSync/shared/Models/Masternode/DSSimplifiedMasternodeEntry+Mndiff.m
DashSync/shared/Models/Masternode/DSSimplifiedMasternodeEntry.m

Reduce memory consumption
Overall, with these small changes we were able to save extra 100-200mb of RAM.
Profiler, Manually 
N/A

feat: Reduce memory consumption

---

DashSync.podspec
Example/Podfile.lock

Switch off some heavy logs on rust side

[DashSharedCore 0.4.0]

---

DashSync/shared/Models/Network/DSPeer.m

Fix: limit upper bound for protocol version, since it could have api changes
Tested locally with the simulator

fix: limit protocol version support with upper bound

---

DashSync/shared/Models/Managers/Chain Managers/DSMasternodeManager.m
DashSync/shared/Models/Network/DSPeer.m

Fix for filename suffix (protocol version) for storing list diffs
Tested locally

chore: Merge develop into master

---

Example/DashSync/DSCreateBlockchainIdentityViewController.m
Example/DashSync/DSCreateInvitationViewController.m

Just adapt changed identity methods for example app

chore: adapt changed identity methods for example app

---

DashSync.podspec
Example/Podfile.lock

- core v0.20 hard fork activation height 1987776

DashSharedCore 0.4.16

---

DashSync/shared/Models/CoinJoin/DSTransaction+CoinJoin.h
DashSync/shared/Models/CoinJoin/DSTransaction+CoinJoin.m
DashSync/shared/Models/CoinJoin/DSTransactionInput+CoinJoin.h
DashSync/shared/Models/CoinJoin/DSTransactionInput+CoinJoin.m
DashSync/shared/Models/CoinJoin/DSTransactionOutput+CoinJoin.h
DashSync/shared/Models/CoinJoin/DSTransactionOutput+CoinJoin.m
DashSync/shared/Models/Managers/Chain Managers/DSPeerManager.m
DashSync/shared/Models/Wallet/DSAccount.h
DashSync/shared/Models/Wallet/DSAccount.m
DashSync/shared/Models/Wallet/DSWallet.h
DashSync/shared/Models/Wallet/DSWallet.m
Example/DashSync.xcodeproj/project.pbxproj
Example/DashSync/Actions.storyboard
Example/DashSync/Base.lproj/Main.storyboard
Example/DashSync/DSActionsViewController.m
Example/DashSync/DSCoinJoinViewController.h
Example/DashSync/DSCoinJoinViewController.m

To proceed with CoinJoin development, we should be able to callback DashSync from DashSharedCore for some peer-to-peer information, as well as trigger CoinJoin from the Example app.
- Entry points for CoinJoin in the Example app.
- Callbacks for input and chain lock checks.
- Memory management.
N/A

feat(coinjoin): first steps for DashSync <-> DashSharedCore integration

---

DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.h
DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.m
DashSync/shared/Models/CoinJoin/DSTransaction+CoinJoin.h
DashSync/shared/Models/CoinJoin/DSTransaction+CoinJoin.m
DashSync/shared/Models/Wallet/DSAccount.m
Example/DashSync.xcodeproj/project.pbxproj
Example/DashSync/DSCoinJoinViewController.h
Example/DashSync/DSCoinJoinViewController.m
Example/Podfile.lock

Callbacks for https://github.com/dashpay/dash-shared-core/pull/63

feat(coinjon): create_denominated callbacks

---

DashSync/shared/Models/Chain/DSChain.m
DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.h
DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.m
DashSync/shared/Models/Derivation Paths/DSDerivationPath.h
DashSync/shared/Models/Derivation Paths/DSDerivationPath.m
DashSync/shared/Models/Derivation Paths/DSFundsDerivationPath.h
DashSync/shared/Models/Derivation Paths/DSFundsDerivationPath.m
DashSync/shared/Models/Wallet/DSAccount.h
DashSync/shared/Models/Wallet/DSAccount.m
Example/DashSync/DSCoinJoinViewController.m

The outputs created by `create_denominated` need to be sent to CoinJoin addresses.
- CoinJoin derivation path
- Commit callbacks
N/A

feat(coinjoin): commit transaction

---

DashSync/shared/Models/CoinJoin/DSCoinControl.h
DashSync/shared/Models/CoinJoin/DSCoinControl.m
DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.h
DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.m
DashSync/shared/Models/Wallet/DSAccount.h
DashSync/shared/Models/Wallet/DSAccount.m
DashSync/shared/Models/Wallet/DSWallet+Protected.h
DashSync/shared/Models/Wallet/DSWallet.m
Example/DashSync/Contacts.storyboard
Example/DashSync/DSCoinJoinViewController.m
Example/DashSync/Wallets.storyboard

- `availableCoins` method is exposed to be used from dash-shared-core
- `hasCollateralInputs` is moved to Rust
- Refactored the no-prompt seedRequestBlock to be a method
N/A

feat(coinjoin): refactor no prompt signing and availableCoins

---

DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.h
DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.m
Example/DashSync/DSCoinJoinViewController.m

- Callbacks for CoinJoinClientManager
N/A

feat(coinjoin) ClientManager callbacks

---

DashSync.podspec
DashSync/shared/Models/CoinJoin/DSCoinJoinManager.m
DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.h
DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.m
DashSync/shared/Models/Managers/Chain Managers/DSPeerManager.h
DashSync/shared/Models/Messages/CoinJoin/DSCoinJoinAcceptMessage.h
DashSync/shared/Models/Messages/CoinJoin/DSCoinJoinAcceptMessage.m
DashSync/shared/Models/Network/DSPeer.h
DashSync/shared/Models/Network/DSPeer.m
Example/Podfile.lock

Callbacks for sending messages. Isn't actually tested yet since the whole CoinJoin flow needs to be rechecked to ensure it gets to this point.

feat(coinjoin): send message callbacks

---

DashSync/shared/Models/CoinJoin/DSCoinJoinManager.h
DashSync/shared/Models/CoinJoin/DSCoinJoinManager.m
DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.h
DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.m
DashSync/shared/Models/CoinJoin/Utils/DSMasternodeGroup.h
DashSync/shared/Models/CoinJoin/Utils/DSMasternodeGroup.m
DashSync/shared/Models/Managers/Chain Managers/DSPeerManager.h
DashSync/shared/Models/Managers/Chain Managers/DSPeerManager.m
DashSync/shared/Models/Messages/CoinJoin/DSCoinJoinAcceptMessage.h
DashSync/shared/Models/Messages/CoinJoin/DSSendCoinJoinQueue.h
DashSync/shared/Models/Messages/CoinJoin/DSSendCoinJoinQueue.m
Example/DashSync/DSCoinJoinViewController.m
Example/Podfile.lock

- CoinJoin sends `SENDDSQ` to any connected peer.
- `MasternodeGroup` in DashJ is responsible for CoinJoin connectivity management.
- `MasternodeGroup` draft
- SENDDSQ sending
N/A

feat(coinjoin): senddsq & MasternodeGroup draft

---

DashSync/shared/Models/CoinJoin/DSCoinJoinManager.h
DashSync/shared/Models/CoinJoin/DSCoinJoinManager.m
DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.h
DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.m
DashSync/shared/Models/CoinJoin/Utils/DSMasternodeGroup.h
DashSync/shared/Models/CoinJoin/Utils/DSMasternodeGroup.m
DashSync/shared/Models/Messages/CoinJoin/DSCoinJoinAcceptMessage.m
DashSync/shared/Models/Messages/CoinJoin/DSCoinJoinEntryMessage.h
DashSync/shared/Models/Messages/CoinJoin/DSCoinJoinEntryMessage.m
DashSync/shared/Models/Network/DSPeer.h
DashSync/shared/Models/Network/DSPeer.m

- Implement sending DSI message
- Added support for sending different message types
- Added relevant connectivity management logic to `MasternodeGroup`
- Some `client_queue_manager` refactoring
N/A

feat(coinjoin): send dsi

---

DashSync/shared/Models/CoinJoin/DSCoinJoinManager.h
DashSync/shared/Models/CoinJoin/DSCoinJoinManager.m
DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.h
DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.m
DashSync/shared/Models/CoinJoin/DSCompactTallyItem.m
DashSync/shared/Models/CoinJoin/DSInputCoin.m
DashSync/shared/Models/Network/DSPeer.h
DashSync/shared/Models/Network/DSPeer.m
Example/DashSync/DSCoinJoinViewController.m

DSQ message has to be processed
- Processing logic
- Some refactoring
N/A

feat(coinjoin): process dsq

---

DashSync/shared/Models/CoinJoin/DSCoinJoinManager.h
DashSync/shared/Models/CoinJoin/DSCoinJoinManager.m
DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.h
DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.m
DashSync/shared/Models/CoinJoin/Utils/DSMasternodeGroup.h
DashSync/shared/Models/CoinJoin/Utils/DSMasternodeGroup.m
DashSync/shared/Models/Managers/Chain Managers/DSMasternodeManager.h
DashSync/shared/Models/Managers/Chain Managers/DSMasternodeManager.m
DashSync/shared/Models/Network/DSPeer.h
DashSync/shared/Models/Network/DSPeer.m

DSSU and DSQ messages need to be processed
- Processing of DSSU and DSQ
- MasternodeGroup improvements
N/A

feat(coinjoin): process dssu & dsc

---

DashSync/shared/Models/CoinJoin/DSCoinJoinManager.h
DashSync/shared/Models/CoinJoin/DSCoinJoinManager.m
DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.h
DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.m
DashSync/shared/Models/CoinJoin/Utils/DSMasternodeGroup.h
DashSync/shared/Models/CoinJoin/Utils/DSMasternodeGroup.m
DashSync/shared/Models/Managers/Chain Managers/DSPeerManager.m

- Process dstx
- Continue developing `MasternodeGroup` and connection management
N/A

feat(coinjoin): masternode group improvements

---

DashSync/shared/Models/CoinJoin/DSCoinJoinManager.h
DashSync/shared/Models/CoinJoin/DSCoinJoinManager.m
DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.h
DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.m
DashSync/shared/Models/CoinJoin/Utils/DSMasternodeGroup.m
DashSync/shared/Models/Network/DSPeer.m
Example/DashSync/DSCoinJoinViewController.m

- Some reorg and additional functionality is needed to establish the correct execution flow of CoinJoin
- Some multithreading fixes
- Some peer management fixes

fix(coinjoin): reorg and bug fixes

---

DashSync/shared/Models/Managers/Service Managers/DSPriceManager.m

fix: we should store default currency initially

---

DashSync/shared/Models/CoinJoin/DSCoinJoinManager.h
DashSync/shared/Models/CoinJoin/DSCoinJoinManager.m
DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.m
DashSync/shared/Models/CoinJoin/DSTransaction+CoinJoin.m
DashSync/shared/Models/CoinJoin/DSTransactionOutput+CoinJoin.m
DashSync/shared/Models/CoinJoin/Utils/DSMasternodeGroup.m
DashSync/shared/Models/Network/DSPeer.m
DashSync/shared/Models/Transactions/Base/DSTransaction.m
DashSync/shared/Models/Wallet/DSAccount.m
Example/DashSync/Wallets.storyboard
Example/Tests/DSCoinJoinSessionTest.m

For sending signed inputs (dss message), we need to support SIGHASH_ANYONECANPAY.
- SIGHASH_ANYONECANPAY support
- Some fixes for proper input signing

fix(coinjoin): SIGHASH_ANYONECANPAY and proper serialization

---

DashSync/shared/Models/CoinJoin/DSCoinJoinManager.h
DashSync/shared/Models/CoinJoin/DSCoinJoinManager.m
DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.h
DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.m
DashSync/shared/Models/CoinJoin/Utils/DSMasternodeGroup.m
DashSync/shared/Models/Network/DSPeer.m
DashSync/shared/Models/Wallet/DSAccount.h
DashSync/shared/Models/Wallet/DSAccount.m
Example/DashSync/DSTransactionsViewController.m

We need some events to hook into and listen to for the wallet integration.
- Events and event listeners
- Transactions screen updated to reflect CJ transaction types

feat: event listeners

---

DashSync/shared/Models/CoinJoin/DSCoinJoinManager.h
DashSync/shared/Models/CoinJoin/DSCoinJoinManager.m
DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.h
DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.m
DashSync/shared/Models/CoinJoin/Utils/DSMasternodeGroup.m
DashSync/shared/Models/Wallet/DSAccount.h
DashSync/shared/Models/Wallet/DSAccount.m
Example/DashSync/DSCoinJoinViewController.m

Running CoinJoin with several sessions is buggy.
- `isWaitingForNewBlock` fixes
- Refreshing unused keys
- mixingStarted event
N/A

fix(coinjoin): multisession fixing & refresh unused keys

---

DashSync/shared/Models/CoinJoin/DSCoinJoinManager.m

Balance calculation for CoinJoin checks every output in transactions that have utxos, while only utxos themselves should be considered.
- Fixed balance calculations

fix(coinjoin): balance calculation

---

DashSync/shared/Models/Network/DSPeer.m

Disable max protocol version check

chore: disable max proto version check

---

DashSync/shared/DashSync.m
DashSync/shared/Models/CoinJoin/DSCoinControl.h
DashSync/shared/Models/CoinJoin/DSCoinControl.m
DashSync/shared/Models/CoinJoin/DSCoinJoinManager.h
DashSync/shared/Models/CoinJoin/DSCoinJoinManager.m
DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.h
DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.m
DashSync/shared/Models/CoinJoin/Utils/DSMasternodeGroup.m
DashSync/shared/Models/Managers/Chain Managers/DSTransactionManager.m

`MasternodeGroup` has some crashes related to concurrent mutability and synchronization.
- Improved synchronization
- CoinControl improvements
- Network switch improvements
QA

fix(coinjoin): masternodegroup crashes

---

DashSync/shared/Models/CoinJoin/DSCoinJoinManager.h
DashSync/shared/Models/CoinJoin/DSCoinJoinManager.m
DashSync/shared/Models/CoinJoin/DSCoinJoinWrapper.m
DashSync/shared/Models/CoinJoin/Utils/DSMasternodeGroup.m
DashSync/shared/Models/Managers/Chain Managers/DSTransactionManager.m
Example/Podfile.lock

- `commitTransactionForAmounts` crashes due to the "already borrowed" error in Rust
- Posting `DSChainBlockWasLockedNotification` crashes, possibly due to nil `block`
- `pendingClosingMasternodes` crashes due to wrong result type
- Crash fixes
- Logging improvements
QA

fix(coinjoin): crash fixes & logging improvements

---

DashSync/shared/Models/Platform/Transitions/BlockchainIdentity/DSBlockchainIdentityCloseTransition.m
DashSync/shared/Models/Platform/Transitions/BlockchainIdentity/DSBlockchainIdentityUpdateTransition.m
DashSync/shared/Models/Transactions/Base/DSTransaction.h
DashSync/shared/Models/Transactions/Base/DSTransaction.m
DashSync/shared/Models/Transactions/Coinbase/DSCoinbaseTransaction.m
DashSync/shared/Models/Transactions/Provider/DSProviderRegistrationTransaction.m
DashSync/shared/Models/Transactions/Provider/DSProviderUpdateRegistrarTransaction.m
DashSync/shared/Models/Transactions/Provider/DSProviderUpdateRevocationTransaction.m
DashSync/shared/Models/Transactions/Provider/DSProviderUpdateServiceTransaction.m
DashSync/shared/Models/Transactions/Quorums/DSQuorumCommitmentTransaction.m

Fix: special tx hashing
Incorrect polymorphism of special transactions fixed which led to incorrect tx hashing & tx processing & sync issues

fix: incorrect polymorphism

---

DashSync.podspec
Example/Podfile
Example/Podfile.lock

Bump up DashSharedCore to [0.4.19](https://github.com/dashpay/dash-shared-core/releases/tag/0.4.19)

chore: bump up DashSharedCore to 0.4.19

---

DashSync/shared/Models/Transactions/Base/DSAssetLockTransaction.m
DashSync/shared/Models/Transactions/Base/DSAssetUnlockTransaction.m

Some users have the sync stuck because of asset lock tx. The polymorphism fixes were not ported to the new tx type.
- Fixed polymorphism.
QA

fix(coinjoin): polymorphism

---

DashSync.podspec
DashSync/shared/Models/Identity/DSBlockchainIdentity.h
DashSync/shared/Models/Identity/DSBlockchainIdentity.m
DashSync/shared/Models/Identity/DSBlockchainInvitation.h
DashSync/shared/Models/Identity/DSBlockchainInvitation.m

Some `Nullable` annotations required for better Swift interop
- Nullable annotations
- Bump dash-shared-core version
QA

fix: swift interop for invites
